### ISSUE TITLE
Rename german menu link to english and add pages to main menu

### ISSUE THREAD

**Issue by mariam58** [bitoid/bksi#134]
- [x] Rename tragwerksplanung page into Structural Engineering;
- [x] Rename projektdetailseite page into Product Detail;
- [x] Rename stellendetailseite page into Job Detail;
- [ ] Add correct pages into main menu;
- [ ] Export page and menu link using DC module in bksi_default_content module;

**Comment by sepishvili** [comment]
http://bksi.docker.localhost:8000/projektdetail es saertod wasashelia igives aketebs es gverdi http://bksi.docker.localhost:8000/node/16 , project content type
