### ISSUE TITLE
Create `Offer` custom block type for `Career page`

### ISSUE THREAD

**Issue by giorgitchanturidze** [bitoid/bksi#28]
[Career Page on Github Pages](https://chkhikvadzeg.github.io/BKSI/src/karriere.html)

- [x] Install Paragraphs module: https://www.drupal.org/project/paragraphs;
- [x] Create new paragraph type called `Offer`
- [x] Fields to be added into `Offer` paragraph type: Title, Item.
- [x] Create custom block type called `Offer`;
- [x] Add `slogan` text field for Offer block;
- [x] Add `title` text field for Offer block;
- [x] Add `description` text field for Offer block;
- [x] Add Paragraph reference field to Offer block - choose Offer as a target paragraph, allow multiple cardinality;
- [x]  Add block template from markup;

![image](https://user-images.githubusercontent.com/101937929/185470208-10ae5b29-b5de-480f-b216-205667f17c43.png)

**Comment by Anemoiaa** [comment]
ამ ბრენჩიდან ინსტალაციის დროს ```docker compose exec php drush site:install --existing-config --account-pass=1234```
მეუბნება რომ ```paragraph``` მოდული არ არსებობს და ხელით მიწევს დაყენება
```composer.json``` ეგ დეფენდესი გაწერილია და წესით უნდა აყენებდეს. ვერ ვხვდები რისი ბრალია.
```paragraph``` მოდული რომ დავაყენე ```composer.lock```  არ გავაყოლე გიტზე
მხოლოდ composer.json გავუშვი და მაგის ბრალი ჰო არ იქნება?

**Comment by Anemoiaa** [comment]
https://github.com/bitoid/bksi/issues/28#issuecomment-1221012521
**[FIX]**
```composer.lock``` -ის დამატებამ უშვლე.
თუ ინსტალაციისას მაინც პრობლემა შეიქმნა - დააყენეთ ```paragraphs``` მოდული  ```docker composer exec php composer require 'drupal/paragraphs:^1.14'```

**Comment by KhatunaKhatuna** [comment]
good job! 

works properly if:

1. before drush cim install paragraph module:  docker composer exec php composer require 'drupal/paragraphs:^1.14'
2. create bksi.them and use: hook_theme_suggestions_HOOK_alter().
