### ISSUE TITLE
Create `Application` custom block type for `Career page`

### ISSUE THREAD

**Issue by giorgitchanturidze** [bitoid/bksi#30]
[Career Page on Github Pages](https://chkhikvadzeg.github.io/BKSI/src/karriere.html)

- [x] Create `Application` paragraph type;
- [x] Add fields to Application paragraph type: accordion item with body;
- [x] Create custom block type called `Application`;
- [x] Add `Image` image field for Application block;
- [x] Add `Slogan` text field for Application block;
- [x] Add `Title` text field for Application block;
- [x] Add Paragraph reference filed to Application custom block type using Application target as paragraph type, with multiple cardinality;

![image](https://user-images.githubusercontent.com/101937929/185489014-298027eb-7ed8-461b-b13a-d434080c61a6.png)

**Comment by pllague** [comment]
Done
