### ISSUE TITLE
Implement Text Section with CTA

### ISSUE THREAD

**Issue by otarza** [bitoid/bksi#4]
- [x] Implement custom block type called "Text Section with CTA";
- [x] Add text field called Slogan;
- [x] Add text field called Title;
- [x] Add long text field called Paragraph;
- [x] Add Link field called Link CTA;
- [x] Add block template from markup;

![Screenshot from 2022-08-16 12-21-55](https://user-images.githubusercontent.com/1330491/184833027-5e84d589-1770-4ba3-98fb-f0977278840e.png)

**Comment by Anemoiaa** [comment]
To add this block on the page:
1. Go to **admin/structure/block/block-content** 
2. Click **add custom block**  and select **'Text Sectin with CTA'**
3. Next step is insert this block to some region (admin/structure/block)

Contact:
Email: **georgiypetroff@gmail.com**
Discord: **Angope#5510**
