### ISSUE TITLE
Create `Team Gallery` custom block type for `Team page`

### ISSUE THREAD

**Issue by giorgitchanturidze** [bitoid/bksi#43]
[Team Page on Github Pages](https://chkhikvadzeg.github.io/BKSI/src/team.html)

- [x] Create `Team Gallery` paragraph type;
- [x] Add fields to `Team Gallery` paragraph type: Image Align (Left|Right);
- [x] Create custom block type called `Team Gallery`;
- [x] Add `Title` text field for Team Gallery block;
- [x] Add Paragraph reference filed to Team Gallery custom block type using Team Gallery target as paragraph type, with multiple cardinality;

![image](https://user-images.githubusercontent.com/101937929/185555204-24aab9df-48df-443b-abd4-680cc62cf75b.png)

**Comment by DavitKheoshvili** [comment]
Task done, tested and merged. Closing issue
