### ISSUE TITLE
Create and Export `Customers` page using DC module

### ISSUE THREAD

**Issue by giorgitchanturidze** [bitoid/bksi#44]
[Customers Page on Github Pages](https://chkhikvadzeg.github.io/BKSI/src/kunden.html)

- [x] Add `Customers` Page using Page content type;
- [x] Install `Default Content` module https://www.drupal.org/project/default_content;
- [x] Create new custom module called `bksi_default_content`;
- [x] Export `Customers Page` using DC module;

**Comment by DavitKheoshvili** [comment]
Task done, tested and merged. Closing issue
