### ISSUE TITLE
Create `Web Form` Block Type for `Ask Detail Page`

### ISSUE THREAD

**Issue by giorgitchanturidze** [bitoid/bksi#49]
[Ask Detail page Page on Github Pages](https://chkhikvadzeg.github.io/BKSI/src/stellendetailseite.html)

- [ ] Create custom block type called `Web Form`;
- [ ] Add `Title` text field for Web Form block;
- [ ] Add `Web Form` with `Name` `Surname` `E-Mail` `Phone` `Information` `Upload` `Checkbox` fields;
- [ ] Use Formdazzle Module to style form - https://www.drupal.org/project/formdazzle;

> Added custom background to detect checkbox and upload buttons (_You can see original template on top of this task_)
![image](https://user-images.githubusercontent.com/101937929/185562769-9d82208f-a67a-43d7-b823-c54687bb46ac.png)

**Comment by Anemoiaa** [comment]
- [ ] Crete custom module called bksi_contact_form;
- [ ] Implement custom block plugin called bksi_contact_form;
- [ ] Implement custom form called ContactForm;
- [ ] Add tmeplate from markup;
- [ ]  Use Formdazzle Module to style form - https://www.drupal.org/project/formdazzle;

**Comment by Anemoiaa** [comment]
**Before testing**

1. Install Font-awesome (see: https://github.com/bitoid/bksi/pull/25#issuecomment-1224842716)
2. Copy code from https://github.com/Chkhikvadzeg/BKSI/blob/master/style/style.css to src/tailwind.pcss
3. Copy config from https://github.com/Chkhikvadzeg/BKSI/blob/master/tailwind.config.js to tailwind.config.js, **don't copy `content variable`** 
4. Run `npm install`
5. Run `npm install -D tailwindcss-hyphens`
6. Run `npm run dev`
