### ISSUE TITLE
Create and Export `Ask Projects Detailed` page using DC module

### ISSUE THREAD

**Issue by giorgitchanturidze** [bitoid/bksi#54]
[Ask Projects Detailed page Page on Github Pages](https://chkhikvadzeg.github.io/BKSI/src/projektdetailseite.html)

- [x] Add `Ask Projects Detailed` Page using Page content type;
- [x] Install `Default Content` module https://www.drupal.org/project/default_content;
- [x] Create new custom module called `bksi_default_content`;
- [x] Export `Ask Projects Detailed Page` using DC module;

**Comment by mariam58** [comment]
Default Content module https://www.drupal.org/project/default_content is already installed;
Custom module called bksi_default_content is already created;
