### ISSUE TITLE
Implement Company Details custom block type

### ISSUE THREAD

**Issue by otarza** [bitoid/bksi#6]
- [x] Create Company Detail paragraph type;
- [x] Add fields to company detail paragraph type: Image, Image Align (Left|Right), Slogan, Title, Description, Link CTA;
- [x] Create Company Details custom block type;
- [x] Add Paragraph reference filed to Company Details custom block type using Company Detail target as paragraph type, with multiple cardinality;

**Comment by DavitKheoshvili** [comment]
Task done, tested and merged. Closing issue
