### ISSUE TITLE
Style `Ask Projects Detailed` node page

### ISSUE THREAD

**Issue by giorgitchanturidze** [bitoid/bksi#67]
[Ask Projects Detailed page Page on Github Pages](https://chkhikvadzeg.github.io/BKSI/src/projektdetailseite.html)

- [ ] Find and style `Ask Projects Detailed` template;

![image](https://user-images.githubusercontent.com/101937929/185731566-798cc2d2-8c4d-4bb0-b82c-878385dd88ed.png)

**Comment by sepishvili** [comment]
რამოდენიმე ფილდის დამატება მომიწევს. მარჯვნივ მესამე დიდი ტექსტის. და მარცხნივ მშენებელი კომპანიის გრაფის
